---
# tasks file for ansible-refind

- name: '[refind] Download latest rEFInd prebuilt binary'
  get_url:
    url: https://sourceforge.net/projects/refind/files/latest/download/
    dest: "/tmp"
  register: refind_zip
  tags: refind

- name: '[refind] Unarchive rEFInd'
  unarchive:
    src: "{{ refind_zip.dest }}"
    dest: "/tmp"
    remote_src: yes
  tags: refind

- name: '[refind] Check if /usr/local/bin/mountesp binary exists'
  stat:
    path: /usr/local/bin/mountesp
  register: refind_mountesp
  tags: refind

- name: '[refind] Run refind-install OSX/Linux installation wrapper script'
  command: "{{ refind_zip.dest | replace('.zip', '') }}/refind-install"
  become: yes
  register: refind_install
  when: not refind_mountesp.stat.exists or refind_force_install
  tags: refind

- name: '[refind] Check if /Volumes/ESP is mounted'
  command: mount
    warn=no  # Ugly, but must use '=' instead of ':'
  register: refind_mount
  changed_when: false
  tags: refind

- name: '[refind] Mount ESP volume under /Volumes/ESP'
  command: mountesp
  register: refind_mountesp_result
  become: yes
  changed_when: "'The ESP is mounted at /Volumes/ESP' in refind_mountesp_result.stdout"
  when:
  - refind_mountesp.stat.exists
  - not refind_install.changed
  - "'/Volumes/ESP' not in refind_mount.stdout"
  # - ansible_mounts | selectattr('mount','equalto','/Volumes/ESP') | list | count > 0
  tags: refind

- name: '[refind] Copy custom rEFInd OS icons'
  copy:
    src: icons/
    dest: /Volumes/ESP/EFI/refind/icons/
  tags: refind

- name: '[refind] Copy rEFInd config'
  copy:
    src: refind.conf
    dest: /Volumes/ESP/EFI/refind/
  tags: refind
